import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { CalendarDays, Search } from 'lucide-react';
import { getStudentOverview } from '../../services/studentOverview.js';

export const CalendarPage: React.FC = () => {
  const [search, setSearch] = useState('');
  const overviewQuery = useQuery({ queryKey: ['student', 'overview'], queryFn: getStudentOverview });
  const events = useMemo(() => (overviewQuery.data?.events || []).filter((event) => `${event.title} ${event.courseTitle || ''}`.toLowerCase().includes(search.toLowerCase())), [overviewQuery.data?.events, search]);
  return <div className="space-y-6 p-4 md:p-6 lg:p-8"><header className="flex flex-col justify-between gap-4 rounded-3xl border border-[#eee9df] bg-white p-6 shadow-sm sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#615a77]">Jadwal pembelajaran</p><h1 className="mt-2 text-3xl font-bold text-zinc-900">Kalender saya</h1><p className="mt-1 text-sm text-stone-500">Event kursus yang terhubung dari jadwal admin.</p></div><label className="flex items-center gap-2 rounded-full bg-[#f6f3ed] px-3 py-2"><Search size={16} className="text-stone-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari event" className="w-48 bg-transparent text-xs outline-none" /></label></header><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{events.map((event) => <article key={event.id} className="rounded-3xl border border-[#eee9df] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#e4dbfe] text-[#615a77]"><CalendarDays size={18} /></span><span className="rounded-full bg-[#e8efc8] px-2.5 py-1 text-[10px] font-bold text-[#58701c]">{event.type}</span></div><h2 className="mt-4 font-bold text-zinc-900">{event.title}</h2><p className="mt-1 text-xs text-stone-500">{event.courseTitle || 'Kursus'} </p><p className="mt-4 text-sm font-semibold text-[#615a77]">{new Date(event.start).toLocaleString('id-ID', { dateStyle: 'full', timeStyle: 'short' })}</p>{event.description && <p className="mt-2 text-xs leading-5 text-stone-500">{event.description}</p>}{event.link && <a href={event.link} target="_blank" rel="noreferrer" className="mt-4 inline-flex text-xs font-bold text-[#615a77]">Buka tautan acara</a>}</article>)}</section>{!overviewQuery.isLoading && !events.length && <div className="rounded-3xl bg-white p-10 text-center text-sm text-stone-500">Belum ada jadwal untuk kursus yang diikuti.</div>}</div>;
};

export default CalendarPage;
