import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Download, FileText, Search } from 'lucide-react';
import { getStudentOverview } from '../../services/studentOverview.js';

export const LibraryPage: React.FC = () => {
  const [search, setSearch] = useState('');
  const [type, setType] = useState<'all' | 'pdf' | 'video'>('all');
  const overviewQuery = useQuery({ queryKey: ['student', 'overview'], queryFn: getStudentOverview });
  const assets = useMemo(() => (overviewQuery.data?.courses || []).flatMap((course) => course.materials.map((material) => ({ ...material, courseTitle: course.title }))).filter((material) => (type === 'all' || (type === 'pdf' ? material.type === 'pdf' : material.type !== 'pdf')) && `${material.title} ${material.courseTitle}`.toLowerCase().includes(search.toLowerCase())), [overviewQuery.data?.courses, search, type]);
  return <div className="space-y-6 p-4 md:p-6 lg:p-8"><header className="flex flex-col justify-between gap-4 rounded-3xl border border-[#eee9df] bg-white p-6 shadow-sm sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#615a77]">Materi terdaftar</p><h1 className="mt-2 text-3xl font-bold text-zinc-900">Library saya</h1><p className="mt-1 text-sm text-stone-500">File dan video dari kursus yang Anda ikuti.</p></div><label className="flex items-center gap-2 rounded-full bg-[#f6f3ed] px-3 py-2"><Search size={16} className="text-stone-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari materi" className="w-48 bg-transparent text-xs outline-none" /></label></header><div className="flex gap-2"><button onClick={() => setType('all')} className={`rounded-full px-4 py-2 text-xs font-bold ${type === 'all' ? 'bg-[#1c1d22] text-white' : 'bg-white text-stone-600'}`}>Semua</button><button onClick={() => setType('pdf')} className={`rounded-full px-4 py-2 text-xs font-bold ${type === 'pdf' ? 'bg-[#1c1d22] text-white' : 'bg-white text-stone-600'}`}>PDF</button><button onClick={() => setType('video')} className={`rounded-full px-4 py-2 text-xs font-bold ${type === 'video' ? 'bg-[#1c1d22] text-white' : 'bg-white text-stone-600'}`}>Video</button></div><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{assets.map((asset) => <article key={asset.id} className="rounded-3xl border border-[#eee9df] bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#e4dbfe] text-[#615a77]"><FileText size={18} /></span><span className="rounded-full bg-[#f6f3ed] px-2.5 py-1 text-[10px] font-bold uppercase text-stone-500">{asset.type}</span></div><h2 className="mt-4 font-bold text-zinc-900">{asset.title}</h2><p className="mt-1 text-xs text-stone-500">{asset.courseTitle} · {asset.durationMinutes} menit</p>{asset.description && <p className="mt-3 line-clamp-2 text-xs leading-5 text-stone-500">{asset.description}</p>}{asset.url && <a href={asset.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#1c1d22] px-3 py-2 text-xs font-bold text-white"><Download size={14} />Buka materi</a>}</article>)}</section>{!overviewQuery.isLoading && !assets.length && <div className="rounded-3xl bg-white p-10 text-center text-sm text-stone-500">Belum ada materi yang cocok.</div>}</div>;
};

export default LibraryPage;
